name: dotnet-pipeline-template

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Publish
      if: ${{ inputs.publish }}
      run: dotnet publish -c Release -o ./publish